# Swin Transformer Large Configuration - Fold 3
# For BREAKTHROUGH_STACKING Pipeline

# K-Fold Training
fold: 3
kfold_csv_dir: data/kfold_splits

# Model
model: swin_large_patch4_window12_384
img_size: 384
num_classes: 4

# Training
epochs: 40
batch_size: 6
lr: 0.00005
optimizer: adamw
weight_decay: 0.00025

# Loss
loss: improved_focal
focal_alpha: [1.0, 1.5, 2.0, 12.0]
focal_gamma: 3.5
label_smoothing: 0.12

# Scheduler
scheduler: cosine
warmup_epochs: 5
min_lr: 0.0000005

# Regularization
dropout: 0.3
drop_path_rate: 0.2

# Data Augmentation
mixup_prob: 0.6
mixup_alpha: 1.2
cutmix_prob: 0.5
cutmix_alpha: 1.0

# Geometric augmentation
aug_rotation: 15
aug_translate: 0.1
aug_scale: [0.9, 1.1]
aug_hflip: true
aug_vflip: false

# Advanced augmentation
random_erasing_prob: 0.3
color_jitter: 0.2
gaussian_blur_prob: 0.1

# SWA
use_swa: true
swa_start_epoch: 32
swa_lr: 0.00002

# Early stopping
patience: 12
min_delta: 0.0001

# Output
output_dir: outputs/breakthrough_20251113_004854/layer1/swin_large/fold3
save_best_only: true

# GPU Optimization
mixed_precision: true
cudnn_benchmark: true
channels_last: true
gradient_accumulation_steps: 2
gradient_checkpointing: true
